spring:
  application:
    name: config-client-dev
server:
  port: 3366
#·þÎñ×¢²áµ½eurekaµØÖ·
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
config:
  info: this is main/config-dev.yml
